### ISSUE TITLE
Binary relevance fails when N=2 and class 1 subset of class 2?

### ISSUE THREAD

**Issue by abarthakur** [scikit-multilearn/scikit-multilearn#101] opened 2018-04-13 00:43 UTC
Hello,

I'm using the Binary Relevance classifier with GaussianNB as the base classifier. 
I kept getting index out of bound errors at the predict_proba function of BR.

The stack is as follows 

> a=self.br.predict_proba(test_sample)
> /home/krys1s/Installations/miniconda3/envs/btp1/lib/python3.5/site-packages/skmultilearn/problem_transform/br.py(108)predict_proba()
> self.ensure_input_format(X)))[:, 1] for label in range(self.model_count)]
  /home/krys1s/Installations/miniconda3/envs/btp1/lib/python3.5/site-packages/skmultilearn/problem_transform/br.py(108)<listcomp>()
> self.ensure_input_format(X)))[:, 1] for label in range(self.model_count)]
  /home/krys1s/Installations/miniconda3/envs/btp1/lib/python3.5/site-packages/scipy/sparse/csr.py(304)__getitem__()
> return self._get_submatrix(row, col)
  /home/krys1s/Installations/miniconda3/envs/btp1/lib/python3.5/site-packages/scipy/sparse/csr.py(448)_get_submatrix()
> check_bounds(j0, j1, N)
  /home/krys1s/Installations/miniconda3/envs/btp1/lib/python3.5/site-packages/scipy/sparse/csr.py(443)check_bounds()
> " %d <= %d" % (i0, num, i1, num, i0, i1))

After a bit of investigating, I'm pretty sure the problem is here-

`    
        predictions = [self.ensure_multi_label_from_single_class(
            self.classifiers[label].predict_proba(
            self.ensure_input_format(X)))[:, 1] for label in range(self.model_count)]
`
The value that [:,1] indexes was a 1x1 matrix in my case. The reason was this was binary classification, and in this particular case all the training samples were annotated with this class. Hence no negative examples, and hence a 1x1 matrix and hence an index out of bounds error.

I guess the same thing will happen for N > 2 , if all examples are annotated with a common class. 

I think this scenario can arise, especially if you're planning to implement Homer and all. So, it shouldn't fail.

Or, maybe I'm totally wrong and missed something in my code?

**Comment by ChristianSch** [comment] 2023-03-14 16:45
closing due to missing reproducible example

**Closed by ChristianSch** 2023-03-14 16:45 UTC
