### ISSUE TITLE
Prediction time of single document is same as bunch of 30 documents. Why?

### ISSUE THREAD

**Issue by pinkal08cece** [scikit-multilearn/scikit-multilearn#64] opened 2017-08-01 11:21 UTC
I am using RandomForestClassifier in LabelPowerset method. After train the model, I predict multi-label class for one documents in 3 sec and also predict class for batch of 30 documents in 3 sec.
How this possible? 
It is initialize every time.

**Comment by ChristianSch** [comment] 2017-08-02 09:53
Can you post the relevant code? I'll have a look.

**Comment by niedakh** [comment] 2018-04-02 22:16
I've checked this in several combinations, and it is just not true, but note that the scaling of the classifier will vary with two aspects:
- number of distinct label combinations
- number of samples
- the complexity of the input space per sample - i.e. the time the base classifier needs to process your data point

I was not able to reproduce your case - there is a growth in computation time, and I did find out that LP also needs more profiling (see #51), but closing this at the moment as invalid, but feel free to reopen if more evidence is provided.

**Closed by niedakh** 2018-04-02 22:16 UTC
