### ISSUE TITLE
IterativeStratification use in medical and some datasets ValueError: Only one class present in y_true. ROC AUC score is not defined in that case

### ISSUE THREAD

**Issue by CquptZA** [scikit-multilearn/scikit-multilearn#253] opened 2022-12-01 14:38 UTC
that means for some labels in y[train] that only have zero class , but i am sure that this label at least have two one class samples IterativeStratification does not work well

**Comment by ChristianSch** [comment] 2023-03-14 17:04
closing due to missing reproducible example

**Closed by ChristianSch** 2023-03-14 17:04 UTC
