### ISSUE TITLE
ModuleNotFoundError: No module named 'arff'

### ISSUE THREAD

**Issue by cj2001** [scikit-multilearn/scikit-multilearn#222] opened 2021-10-12 20:30 UTC
I have followed the directions on the webpage to `pip install scikit-multilearn`, but I received the error message: 

```
ModuleNotFoundError: No module named 'arff'
```

Apparently [this issue](https://github.com/scikit-multilearn/scikit-multilearn/issues/163), which is the same thing, was closed a while back, however the documentation has not been updated.  Following the suggestion there of doing a manual `pip install liac-arff` has apparently corrected the problem.  However, it seems that either the build of the package should be fixed or something should be added to the instructions for how to install to reflect this.

**Comment by ChristianSch** [comment] 2023-03-14 16:40
Seems correct to me. Closing because of missing reproduction example.

https://github.com/scikit-multilearn/scikit-multilearn/blob/47e394faf67261a45f75b166daf31eeeac259403/setup.py#L26

**Closed by ChristianSch** 2023-03-14 16:40 UTC
