### ISSUE TITLE
some question about BinaryRelevance using svm(one classes)

### ISSUE THREAD

**Issue by iromise** [scikit-multilearn/scikit-multilearn#56] opened 2017-05-21 15:53 UTC
hello, I am using br to train multi-label,and my target is 
```
[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 1.  1.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 1.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.]]
```
we can see that the fourth column is all zero, so the number of classes is one, and I get the following crash:
```python
Traceback (most recent call last):
  File "multi_model.py", line 157, in <module>
    train_svc_manual()
  File "multi_model.py", line 98, in train_svc_manual
    clf.fit(X_train, y_train)
  File "/usr/local/lib/python2.7/dist-packages/skmultilearn/problem_transform/br.py", line 71, in fit
    X), self.ensure_output_format(y_subset))
  File "/usr/local/lib/python2.7/dist-packages/sklearn/svm/base.py", line 152, in fit
    y = self._validate_targets(y)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/svm/base.py", line 526, in _validate_targets
    % len(cls))
ValueError: The number of classes has to be greater than one; got 1
```
Should the br deal this problem?

**Comment by kajdanowicz** [comment] 2017-05-22 22:22
Hello, 
It is probably caused by the fact that the underlying base classifier within the br is not able to handle one class data. You have only one unique class label in the training set present. 
The error message tells that you need to have at least two unique classes in the dataset.
In case of one class label try to use [OneClassSVM](http://scikit-learn.org/stable/modules/generated/sklearn.svm.OneClassSVM.html)

**Comment by iromise** [comment] 2017-05-23 04:47
yes, the problem is just as you say, but not all the column is one class, and I'd like to use a supervised method, is there any way to use the svc with br? thanks.

**Comment by ljvmiranda921** [comment] 2017-08-29 15:10
Hi, I encountered this problem before. It's expected behavior because the classifier is expecting multi-class data. Although we have OneClassSVM, not all of our data is one-class.

In my case, I have a routine that just prunes these one-label columns and run a traditional classifier (like LinearSVM or SVM from sklearn) on it.

**Comment by niedakh** [comment] 2018-04-03 00:02
Couple of notes in general.

1. Usually a one class column in a multi-label problem's training set means that the training set has been poorly stratified, see http://proceedings.mlr.press/v74/szyma%C5%84ski17a.html and some cited work especially the 2011 paper of Sechidis et. al.

So before you get to oneclasssvm, remember to explore your train-test split and see if you are actually doing this (forcing the model to learn in tough conditions) on purpose or not.

2. if you really have no positive evidence for a label, and you are using binary relevance - thus ignoring label relations, you should just split the model, train one binary relevance classifier for the labels where you have both positive and negative evidence, and another - using ex. oneclasssvm as base classifier - for the other labels - and just merge them back.

I will put this bug into the future work column - perhaps we'll implement a wrapper or something in the future, closing for now.

3. the trickiest case is when the one class label is actually related to something, i.e. there's a mode of distribution depending on it, that's where you probably need to write a wrapper.

**Closed by niedakh** 2018-04-03 00:02 UTC
